### PR TITLE
Accept my Student Management App

### PR DESCRIPTION
**Pull request by HrithikSahu**
# Related Issue
- Added Student Management App 

# Additional Info
- This is Student management system coded with python tkinter and JSON file modules used as database . This is self describing project containing the features like Add new student , Update Student , Delete Student information and Searching class wise information .

# Checklist
- [x] Tests
- [x] Translations
- [x] Documentation
- [x] Starred the repo

# Screenshots
 
Original        | 
:----------------:|
** Screenshot (765) ** |

### CODE REVIEW

**Comment by king-rohit777** [comment]
Update the comments and describe your project a bit . Remove the predefined template of proposed changes , related issue .

**Comment by SaniyaBhargav** [comment]
@HrithikSahu Kindly correct the issue number in the description.

**Review by nishant-giri — CHANGES_REQUESTED** [review]
@HrithikSahu, kindly add complete details about your project in the README file. If possible, add photos too in the document of your project.

**Comment by HrithikSahu** [comment]
Added the Dashboard Screenshot and My details. It's not much to explain guys just a basic python project.

**Comment by HrithikSahu** [comment]
@nishant-giri Check this PR out.

**Comment by nishant-giri** [comment]
@HrithikSahu, kindly make the necessary changes in your initial comment. Remove those lines from the comment which are not required. And provide a brief description of your project in your comment too.

**Comment by HrithikSahu** [comment]
@nishant-giri Is it ok now?

**Comment by nishant-giri** [comment]
@HrithikSahu, kindly remove the lines regarding `Proposed Changes` from your comment, since you are not working on any issue.

**Comment by HrithikSahu** [comment]
@nishant-giri Dude Why is my PR closed without being merged? what else do u need me to do?

**Pull request merged**
